//
//  ShowOrderModels.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/10/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ShowOrderRequest
{
}

struct ShowOrderResponse
{
}

struct ShowOrderViewModel
{
}

struct ShowOrder_GetOrder_Request {
    
    
}

struct ShowOrder_GetOrder_Response {
    
    var order: Order
}

struct ShowOrder_GetOrder_ViewModel {
    
    struct DisplayedOrder {
        
        var id : String
        
        var date: String
        
        var email: String
        
        var name : String
        
        var total: String
    }
    
    var displayedOrder : DisplayedOrder
    
}
