//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/10/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderInteractorInput
{
  func doSomething(request: ShowOrderRequest)
    
    func getOrder(request: ShowOrder_GetOrder_Request)
    
    var order: Order! { get set }
}

protocol ShowOrderInteractorOutput
{
  func presentSomething(response: ShowOrderResponse)
    
    func presentOrder(response: ShowOrder_GetOrder_Response)
}

class ShowOrderInteractor: ShowOrderInteractorInput
{
  var output: ShowOrderInteractorOutput!
  var worker: ShowOrderWorker!
    
    var order: Order!
  
  // MARK: Business logic
  
  func doSomething(request: ShowOrderRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ShowOrderWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ShowOrderResponse()
    output.presentSomething(response)
  }
    
    func getOrder(request: ShowOrder_GetOrder_Request) {
        
        let response = ShowOrder_GetOrder_Response(order: order)
        
        output.presentOrder(response)
    }
    
    
}
