//
//  ShowOrderViewController.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/10/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderViewControllerInput
{
    func displayOrder(viewModel: ShowOrder_GetOrder_ViewModel)
}

protocol ShowOrderViewControllerOutput
{
    func doSomething(request: ShowOrderRequest)
    
    func getOrder(request: ShowOrder_GetOrder_Request)
    
    var order: Order! { get set }
}

class ShowOrderViewController: UIViewController, ShowOrderViewControllerInput
{
  var output: ShowOrderViewControllerOutput!
  var router: ShowOrderRouter!
  
    @IBOutlet weak var orderIDLabel: UILabel!
    @IBOutlet weak var orderDateLabel: UILabel!
    @IBOutlet weak var orderEmailLabel: UILabel!
    @IBOutlet weak var orderNameLabel: UILabel!
    @IBOutlet weak var orderTotalLabel: UILabel!
  
    // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ShowOrderConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
    
    getOrderOnLoad()
  }
  
  // MARK: Event handling
    
    func getOrderOnLoad() {
        
        let request = ShowOrder_GetOrder_Request()
        
        output.getOrder(request)
    }
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ShowOrderRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: ShowOrderViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
    
    func displayOrder(viewModel: ShowOrder_GetOrder_ViewModel) {
        
        let displayedOrder = viewModel.displayedOrder
        
        orderIDLabel.text = displayedOrder.id
        
        orderDateLabel.text = displayedOrder.date
        
        orderEmailLabel.text = displayedOrder.email
        
        orderNameLabel.text = displayedOrder.name
        
        orderTotalLabel.text = displayedOrder.total
    }
}
