//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 2/28/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrderRequest
{
}

struct CreateOrderResponse
{
}

struct CreateOrderViewModel
{
}
