//
//  CreateOrderViewController.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 2/28/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderViewControllerInput
{
//    func displaySomething(viewModel: CreateOrderViewModel)
    
    func displayExpirationDate(viewModel: CreateOrder_FormatExpirationDate_ViewModel)
}

protocol CreateOrderViewControllerOutput
{
//    func doSomething(request: CreateOrderRequest)
    
    var shippingMethods : [String] { get }
    
    func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request)
}

class CreateOrderViewController: UITableViewController, CreateOrderViewControllerInput, UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate
{
    
    var output: CreateOrderViewControllerOutput!
    
    var router: CreateOrderRouter!
    
    // MARK: Text fields
    
    @IBOutlet var textFields: [UITextField]!
    
    // MARK: Shipping methods and expiration date
    
    @IBOutlet weak var shippingMethodTextField: UITextField!
    
    @IBOutlet weak var expirationDateTextField: UITextField!
    
    @IBOutlet var shippingMethodPicker: UIPickerView!
    
    @IBOutlet var expirationDatePicker: UIDatePicker!
    
    @IBAction func expirationDatePickerValueChanged(sender: AnyObject) {
        
        let date = expirationDatePicker.date
        
        let request = CreateOrder_FormatExpirationDate_Request(date: date)
        
        output.formatExpirationDate(request)
    }
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        
        CreateOrderConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        
        
//        doSomethingOnLoad()
        
        configurePickers()
    }
    
    func configurePickers() {
        
        shippingMethodTextField.inputView = shippingMethodPicker
        
        expirationDateTextField.inputView = expirationDatePicker
    }
    
    // MARK: Event handling
    
//    func doSomethingOnLoad()
//    {
//        // NOTE: Ask the Interactor to do some work
//        
//        let request = CreateOrderRequest()
//        
//        output.doSomething(request)
//    }
    
    // MARK: Display logic
    
//    func displaySomething(viewModel: CreateOrderViewModel)
//    {
//        // NOTE: Display the result from the Presenter
//        
//        // nameTextField.text = viewModel.name
//    }
    
    func displayExpirationDate(viewModel: CreateOrder_FormatExpirationDate_ViewModel) {
        
        let date = viewModel.date
        
        expirationDateTextField!.text = date
    }
    
    // MARK: UITableView Delegates
    
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        if let cell = tableView.cellForRowAtIndexPath(indexPath) {
            
            for textField in textFields {
                
                if textField.isDescendantOfView(cell) {
                    
                    textField.becomeFirstResponder()
                }
            }
        }
    }
    
    // MARK: TextField Delegates
    
    func textFieldShouldReturn(textField: UITextField) -> Bool {
        
        textField.resignFirstResponder()
        
        if let index = textFields.indexOf(textField) {
            
            if index < textFields.count - 1 {
                
                let nextTextField = self.textFields[index + 1]
                
                nextTextField.becomeFirstResponder()
            }
        }
        
        return true
    }
    
    // MARK: UIPickerView DataSource
    
    func numberOfComponentsInPickerView(pickerView: UIPickerView) -> Int {
        
        return 1
    }
    
    func pickerView(pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        
        return output.shippingMethods.count
    }
    
    func pickerView(pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        
        return output.shippingMethods[row]
    }
    
    // MARK: UIPickerView Delegates
    
    func pickerView(pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        
        shippingMethodTextField.text = output.shippingMethods[row]
    }
}























