//
//  OrderModels.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/2/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Foundation

struct Order : Equatable {
    
    var id: String?
    
    var date: NSDate?
    
    var email: String?
    
    var firstName: String?
    
    var lastName: String?
    
    var total: NSDecimalNumber?
}

func ==(lhs: Order, rhs: Order) -> Bool
{
    var dateEqual = false
    if let lhsDate = lhs.date, rhsDate = rhs.date {
        dateEqual = lhsDate.timeIntervalSinceDate(rhsDate) < 1.0
    }
    return lhs.id == rhs.id
        && dateEqual
        && lhs.email == rhs.email
        && lhs.firstName == rhs.firstName
        && lhs.lastName == rhs.lastName
        && lhs.total == rhs.total
}