//
//  OrderModels.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/2/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Foundation

struct Order {
    
}
