//
//  ListOrdersModels.swift
//  CleanStore
//
//  Created by Hiep Nguyen on 3/1/16.
//  Copyright (c) 2016 Zyncas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListOrdersRequest
{
}

struct ListOrdersResponse
{
}

struct ListOrdersViewModel
{
}

struct ListOrders_FetchOrders_Request {

}

struct ListOrders_FetchOrders_Response {
    
    var orders: [Order]
}

struct ListOrders_FetchOrders_ViewModel {
    
    struct DisplayedOrder {
        
        var id: String
        var date: String
        var email: String
        var name: String
        var total: String
    }
    
    var displayedOrders: [DisplayedOrder]
}
